name: CI

on:
  push:
    branches: [ 'main', 'test_ci' ]
  pull_request:
    branches: [ '**' ]

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy pytest pytest-cov
          pip install -r requirements.txt
          
      - uses: psf/black@stable
        if: always()
        with:
          options: "--diff --check --config pyproject.toml --verbose"
          src: "./PeriodogramAnalysis"
      - name: Run mypy type check
        if: always()
        run: mypy --config-file pyproject.toml PeriodogramAnalysis
      - name: Run pytest coverage
        if: always()
        run: |
          pytest --cov=PeriodogramAnalysis --cov-fail-under=80
