name: CI

on:
  pull_request:
    branches: [ '**' ]

jobs:
  ruff:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
          src: "./PeriodogramAnalysis"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest pytest-cov
      - name: Run ruff linter
        run: ruff check PeriodogramAnalysis
      - name: Run mypy type check
        run: mypy --config-file pyproject.toml PeriodogramAnalysis
      - name: Run pytest coverage
        run: |
          pytest --cov=PeriodogramAnalysis --cov-fail-under=80
