name: CI

on:
  pull_request:
    branches: [ '**' ]

jobs:
  ruff:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy pytest pytest-cov
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./PeriodogramAnalysis"
          use_pyproject: true
      - name: Run mypy type check
        run: mypy --config-file pyproject.toml PeriodogramAnalysis
      - name: Run pytest coverage
        run: |
          pytest --cov=PeriodogramAnalysis --cov-fail-under=80